pipeline:
  deploy_consul:
    image: ktruckenmiller/ansible:dind
    environment:
      - AWS_DEFAULT_REGION=us-west-2
    commands:
      - ansible-playbook -i ansible_connection=localhost deploy.yml -e region=us-west-2 -vvv
    when:
      event: [push]
      branch: [master]
