AWSTemplateFormatVersion: 2010-09-09
Resources:
  ServiceClient:
    Type: AWS::ECS::Service
    Properties:
      Cluster: kloudcover
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DesiredCount: 2
      TaskDefinition: !Ref TaskClient
      PlacementConstraints:
        - Type: distinctInstance
        - Type: memberOf
          Expression: not(task:group == task:consul-server)
  TaskClient:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      RequiresCompatibilities:
        - "EC2"
      NetworkMode: host
      ContainerDefinitions:
        - Name: consul-client
          DockerLabels:
            Name: consul-client
          Image: consul
          Cpu: 40
          Memory: 256
          Environment:
            - Name: CONSUL_BIND_INTERFACE
              Value: eth0
            - Name: enable_debug
              Value: true
            - Name: AWS_DEFAULT_REGION
              value: !Sub ${AWS::Region}
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ConsulLogGroup
              awslogs-region: !Sub ${AWS::Region}
              awslogs-stream-prefix: consul-client
          EntryPoint: ["/usr/local/bin/docker-entrypoint.sh"]
          Command: ["agent", "-client=0.0.0.0", "-data-dir=/consul/data", "-ui", "-retry-join", "provider=aws tag_key=consul tag_value=member"]

  ServiceServer:
    Type: AWS::ECS::Service
    Properties:
      Cluster: kloudcover
      ServiceName: consul-service-1
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DesiredCount: 1
      TaskDefinition: !Ref TaskServer
      PlacementConstraints:
        - Type: distinctInstance
  TaskServer:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      RequiresCompatibilities:
        - "EC2"
        # - "FARGATE"

      NetworkMode: host

      ContainerDefinitions:
        - Name: consul-server
          DockerLabels:
            Name: consul-server
          Image: consul
          Cpu: 40
          Memory: 128
          Environment:
            - Name: CONSUL_BIND_INTERFACE
              Value: eth0
            - Name: enable_debug
              Value: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ConsulLogGroup
              awslogs-region: !Sub ${AWS::Region}
              awslogs-stream-prefix: consulServer
          EntryPoint: ["/usr/local/bin/docker-entrypoint.sh"]
          Command: ["agent", "-client=0.0.0.0", "-server", "-data-dir=/consul/data", "-bootstrap", "-ui"]
  ConsulLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
