---
- hosts: localhost
  gather_facts: False
  vars:
    region: us-west-2
    # EFS stuff
    vpc_id: vpc-849531e0
    image_id: ami-0062abacb9034c429
    security_group: sg-36ab3149
    kms_key: 4bacdbef-cc46-41fd-b333-2623977cbf83
    efs_subnet:
      - subnet-bc3193d8
      - subnet-ed43849b
    spots:
      - subnet: subnet-bc3193d8
        az: us-west-2a
      - subnet: subnet-ed43849b
        az: us-west-2b
      - subnet: subnet-9b2938c2
        az: us-west-2c
    instance_types:
      - t2.micro
      - m3.medium
      - t2.small
  tasks:
    - shell: cat ../packer/ami.txt
      register: ami
      ignore_errors: true

    - shell: dig +short vpn.kloudcover.com
      register: home_ip

    - set_fact:
        ami_id: "{{ami.stdout}}"
      when: '"ami" in ami.stdout'

    - name: template out server configs
      template:
        src: server-cf.j2.yml
        dest: "server-cf.yml"

    - name: cloudformation deploy
      cloudformation:
        stack_name: consul-server
        template: server-cf.yml
        region: "{{region}}"
        template_parameters:
          VpcId: "{{vpc_id}}"
          ImageId: "{{ ami_id | default(image_id)}}"
          HomeIp: "{{home_ip.stdout}}"
      register: consul

    - debug: var=consul.stack_outputs
