---
- hosts: localhost
  gather_facts: False
  vars:
    region: us-west-2
    # EFS stuff
    vpc_id: vpc-849531e0
    image_id: ami-0062abacb9034c429
    security_group: sg-36ab3149
    kms_key: 4bacdbef-cc46-41fd-b333-2623977cbf83
    efs_subnet:
      - subnet-bc3193d8
      - subnet-ed43849b
    instance_types:
      - t2.micro
      - m3.medium
      - t2.small
    spots:
      - subnet: subnet-bc3193d8
        az: us-west-2a
      - subnet: subnet-ed43849b
        az: us-west-2b
      - subnet: subnet-9b2938c2
        az: us-west-2c

  tasks:
    - shell: cat ../packer/ami.txt
      register: ami
      ignore_errors: true

    - shell: dig +short vpn.kloudcover.com
      register: home_ip

    - set_fact:
        ami_id: "{{ami.stdout}}"
      when: '"ami" in ami.stdout'

    - name: deploy long lived resources
      cloudformation:
        stack_name: consul-long-lived-resources
        template: long_lived_resources.yml
        region: "{{region}}"
        template_parameters:
          VpcId: "{{vpc_id}}"
          HomeIp: "{{home_ip.stdout}}"

    - name: run through templates
      include: stack.yml
      loop: "{{spots}}"
      loop_control:
        loop_var: spot
