---
- hosts: localhost
  gather_facts: False
  vars:
    region: us-west-2
    # EFS stuff
    vpc_id: vpc-849531e0
    image_id: ami-00706db3e8a388b1b
    security_group: sg-36ab3149
    kms_key: 4bacdbef-cc46-41fd-b333-2623977cbf83
    efs_subnet:
      - subnet-bc3193d8
      - subnet-ed43849b

  tasks:
    - shell: cat ../packer/ami.txt
      register: ami
      ignore_errors: true

    - set_fact:
        ami_id: "{{ami.stdout}}"
      when: '"ami" in ami.stdout'

    - name: cloudformation deploy
      cloudformation:
        stack_name: consul-server
        template: server-cf.yml
        region: "{{region}}"
        template_parameters:
          VpcId: "{{vpc_id}}"
          ImageId: "{{ ami_id | default('ami-0067263472a0df1bd')}}"
      register: consul

    - debug: var=consul.stack_outputs
