{% macro include(file) %}{% include(file) %}{% endmacro %}
---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VolumeSize:
    Default: 22
    Type: String
  ImageId:
    Type: String
  HomeIp:
    Type: String
  Subnet:
    Type: String
Resources:
  SpotFleetConsul:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        AllocationStrategy: diversified
        TargetCapacity: 1
        IamFleetRole: !ImportValue consul-long-lived-resources:SpotFleetRoleArn
        LaunchSpecifications:
{% for instance in instance_types %}
        - BlockDeviceMappings:
          - DeviceName: "/dev/xvdcz"
            Ebs:
              DeleteOnTermination: 'true'
              VolumeSize: !Ref VolumeSize
              VolumeType: gp2
          IamInstanceProfile:
            Arn: !ImportValue consul-long-lived-resources:InstanceProfile
          ImageId: !Ref ImageId
          InstanceType: {{instance}}
          KeyName: boston
          WeightedCapacity: 1
          Monitoring:
            Enabled: 'true'
          SecurityGroups:
            - GroupId: !ImportValue consul-long-lived-resources:ConsulBadgeSG
            - GroupId: !ImportValue consul-long-lived-resources:ConsulPort22SG
          SpotPrice: '0.015'
          SubnetId: !Ref Subnet
          TagSpecifications:
            - ResourceType: instance
              Tags:
              - Key: Name
                Value: consul-server
          UserData:
            Fn::Base64:
              Fn::Sub:
                {{ include('user_data.j2.yml') | indent(16) }}
{% endfor %} # instance types
